import os
import json
import hashlib
from datetime import datetime
from pathlib import Path


PM_DIR = ".pm"
DOC_PATH = ".pm/PROJECT.md"
SNAPSHOT_PATH = ".pm/snapshot.json"


class DocWriter:
    def __init__(self, root: str = "."):
        self.root = root
        self.doc_path = os.path.join(root, DOC_PATH)
        self.snapshot_path = os.path.join(root, SNAPSHOT_PATH)
        os.makedirs(os.path.join(root, PM_DIR, "prompts"), exist_ok=True)

    # ── Initial doc creation ───────────────────────────────────────────────

    def write_initial(self, analysis: dict, decisions: list[dict], code_map: dict = None):
        today = datetime.now().strftime("%Y-%m-%d")
        goals = "\n".join(f"- {g}" for g in analysis.get("goals", []))
        stack = ", ".join(analysis.get("stack", ["Unknown"]))

        decision_rows = "\n".join(
            f"| {d['question']} | {d['answer']} | {today} |"
            for d in decisions
        )
        if not decision_rows:
            decision_rows = "| — | — | — |"

        code_map_section = _build_code_map_section(code_map or {})

        doc = f"""# {Path(self.root).resolve().name}

> Generated by pm-agent on {today}

---

## Purpose
{analysis.get('purpose', 'Not determined.')}

## Goals
{goals or '- Not specified.'}

## Stack
{stack}

## Architecture
{analysis.get('architecture', 'Not determined.')}

## Code Map
{code_map_section}

## Design Decisions
| Question | Decision / Answer | Date |
|---|---|---|
{decision_rows}

## Phases
- Phase 1: Initial setup and core functionality
- Phase 2: (add your milestones here)

## Changelog
### {today}
- Project documentation initialized by pm-agent
"""
        with open(self.doc_path, "w", encoding="utf-8") as f:
            f.write(doc)

        self.save_snapshot({})

    # ── Update code map section ────────────────────────────────────────────

    def update_code_map(self, code_map: dict):
        """Regenerate the Code Map section in PROJECT.md."""
        if not os.path.exists(self.doc_path):
            return

        with open(self.doc_path, "r", encoding="utf-8") as f:
            content = f.read()

        new_section = _build_code_map_section(code_map)

        if "## Code Map" in content and "## Design Decisions" in content:
            before = content.split("## Code Map")[0]
            after = "## Design Decisions" + content.split("## Design Decisions")[1]
            content = before + "## Code Map\n" + new_section + "\n" + after
        elif "## Code Map" not in content:
            content = content.replace(
                "## Design Decisions",
                f"## Code Map\n{new_section}\n\n## Design Decisions"
            )

        with open(self.doc_path, "w", encoding="utf-8") as f:
            f.write(content)

    # ── Changelog update ───────────────────────────────────────────────────

    def append_changelog(self, entries: list[str]):
        if not os.path.exists(self.doc_path):
            return
        today = datetime.now().strftime("%Y-%m-%d")

        with open(self.doc_path, "r", encoding="utf-8") as f:
            content = f.read()

        entry_text = "\n".join(f"- {e}" for e in entries)
        today_header = f"### {today}"

        if today_header in content:
            content = content.replace(
                today_header,
                f"{today_header}\n{entry_text}",
                1
            )
        else:
            addition = f"\n### {today}\n{entry_text}\n"
            content = content.replace("## Changelog", f"## Changelog{addition}", 1)

        with open(self.doc_path, "w", encoding="utf-8") as f:
            f.write(content)

    # ── Manual decision append ─────────────────────────────────────────────

    def append_decision(self, text: str):
        if not os.path.exists(self.doc_path):
            print("PROJECT.md not found. Run `pm init` first.")
            return
        today = datetime.now().strftime("%Y-%m-%d")
        row = f"| Manual entry | {text} | {today} |"

        with open(self.doc_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        in_decisions = False
        last_table_row = -1

        for i, line in enumerate(lines):
            if "## Design Decisions" in line:
                in_decisions = True
            if in_decisions and line.startswith("|"):
                last_table_row = i
            if in_decisions and not line.startswith("|") and last_table_row != -1 and i > last_table_row:
                break

        if last_table_row == -1:
            print("Design Decisions table not found in PROJECT.md.")
            return

        lines.insert(last_table_row + 1, row + "\n")

        with open(self.doc_path, "w", encoding="utf-8") as f:
            f.writelines(lines)

    # ── Read doc ───────────────────────────────────────────────────────────

    def read_doc(self) -> str:
        if not os.path.exists(self.doc_path):
            return ""
        with open(self.doc_path, "r", encoding="utf-8") as f:
            return f.read()

    # ── Snapshot management ────────────────────────────────────────────────

    def save_snapshot(self, file_hashes: dict):
        with open(self.snapshot_path, "w") as f:
            json.dump(file_hashes, f, indent=2)

    def load_snapshot(self) -> dict:
        if not os.path.exists(self.snapshot_path):
            return {}
        with open(self.snapshot_path, "r") as f:
            return json.load(f)

    @staticmethod
    def hash_file(path: str) -> str:
        try:
            with open(path, "rb") as f:
                return hashlib.md5(f.read()).hexdigest()
        except Exception:
            return ""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_code_map_section(code_map: dict) -> str:
    if not code_map:
        return "_No code files mapped yet._\n"

    lines = []
    for path in sorted(code_map.keys()):
        entries = code_map[path]
        lines.append(f"\n### {path}")
        for entry in entries:
            lines.append(entry)

    return "\n".join(lines) + "\n"